apiVersion: apps/v1
kind: Deployment
metadata:
  name: streamflix-app
  labels:
    app: streamflix-app
spec:
  replicas: 4
  selector:
    matchLabels:
      app: streamflix-app
  template:
    metadata:
      labels:
        app: streamflix-app
    spec:
      containers:
      - name: streamflix-app
        image: gayathritdocker/streamflix-deployment:1.0
        ports:
        - containerPort: 80
